修复构建问题
ltxhhz/LL-plugin-list-viewer pull request #18
Opened 2024-06-16 15:46 UTC by LanYunDev

已通过npm/yarn的构建测试

2024-06-16 16:39 UTC, ltxhhz requested changes

2024-06-16 16:39 UTC, ltxhhz commented on package.json
这个是完全没有必要的，因为项目已经依赖了 `electron-vite`，而这个库已经依赖了你加的这两个
[npm](https://www.npmjs.com/package/electron-vite?activeTab=code)
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/51697596/bc3b7864-be72-4950-926a-cfcdb8b60b1a)

2024-06-16 16:39 UTC, ltxhhz commented on electron.vite.config.ts
不应该改变原代码样式，应该保留单引号直接添加双引号就可以

2024-06-16 16:42 UTC, LanYunDev commented on package.json
yarn(v1.22.22)版本实测不添加会发生报错

2024-06-16 16:46 UTC, LanYunDev commented on electron.vite.config.ts
已改回原代码样式

2024-06-17 03:25 UTC, ltxhhz commented on package.json
这个并不属于项目问题，如果 npm 正常只有 yarn 不正常，那应该修改的是 yarn

2024-06-17 03:28 UTC, LanYunDev commented on package.json
确实,不过个人建议添加提高兼容性.

2024-06-17 15:23 UTC, ltxhhz commented on package.json
可以加，你把依赖改到 `devDependencies` 里就可以合并了

再者说，官方包管理器都正常，应该是 yarn 来兼容项目而不是项目兼容 yarn

2024-06-17 15:32 UTC, LanYunDev commented on package.json
已经修改

2024-06-17 15:34 UTC, ltxhhz approved these changes

2024-06-17 15:34 UTC, merged